import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import WhatsAppButton from "@/components/WhatsAppButton";
import React from "react";

// Metadados
export const metadata: Metadata = {
  title: "Geremia Bar - Desde 2015",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  return (
    <>
      <Header locale={locale as "pt" | "en"} />
      {children}
      <Footer locale={locale as "pt" | "en"} />
      <WhatsAppButton />
    </>
  );
}
